import { sql } from '../database/database.js';

// Execute a SQL query to retrieve events (limited to 1000)
const logEvents = async () => {
  const result = await sql`SELECT * FROM events LIMIT 1000`;
  console.log('Events are', result);
  return result;
};

export { logEvents };

// Execute a SQL query to retrieve events by event Id
const getEventById = async (eventId) => {
  const result = await sql`SELECT * FROM events WHERE event_id = ${eventId}`;
  return result[0]; // Assuming the 'event_id' column is unique, return the first row
};

export { getEventById };

// Execute a SQL query to insert a new event into the database
export const insertEvent = async (eventData) => {
  const { person_id, type, timestamp, url } = eventData;

  const result = await sql`
    INSERT INTO events (person_id, type, timestamp, url)
    VALUES (${person_id}, ${type}, ${timestamp}, ${url})
    RETURNING event_id;
  `;

  // Assuming the event_id is auto-generated by the database, return the generated event_id
  return result[0].event_id;
};
